@startuml SSO
autonumber
box "客户方"
actor  user order 10 #red 
participant IDP order 20
end box

participant SP order 30
    user -> SP:访问页面
    SP -> user: 重定向到IDP
    user -> IDP:用户到IDP去验证
    IDP -> user : 认证完成
    user -> SP:重定向到SP
@enduml