@startuml shiro登录流程
    start
    :Subject生成 认证令牌;
    note left:主体对象登录
    -> AuthenticationToken;
    :SecurityManager;
    -> 委托给Relam;
    :Realm执行认证;
    if (包含多个域) then (yes)
    while (next 域?)
        :获取账户;
        :验证密码;
    endwhile;
    else (单域)
        :验证账户;
        :验证密码;
    endif
    end
    
@enduml


@startuml 登录流程
    Subject->Subject:生成认证令牌
    Subject->SecurityManager:AuthenticationToken
    SecurityManager->Authenticator:AuthenticationToken
    Authenticator->Realm:AuthenticationToken
    Realm->Realm:取AuthenticationInfo
    Realm->CredentialsMatcher:AuthenticationInfo,AuthenticationToken
    CredentialsMatcher->Realm:success
    Realm->Authenticator:AuthenticationInfo
    Authenticator->SecurityManager:AuthenticationInfo
    
@enduml